const INITIALIZE = 'INITIALIZE'
const INITIALIZE_SUCCESS = 'INITIALIZE_SUCCESS'
const INITIALIZE_ERROR = 'INITIALIZE_ERROR'
const REQUEST_PLANETS = 'REQUEST_PLANETS'
const REQUEST_PLANETS_SUCCESS = 'REQUEST_PLANETS_SUCCESS'
const REQUEST_PLANETS_ERROR = 'REQUEST_PLANETS_ERROR'
const ADD_TO_CART = 'ADD_TO_CART'
const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
const ADD_TO_CART_ERROR = 'ADD_TO_CART_ERROR'


export {
  INITIALIZE,
  INITIALIZE_SUCCESS,
  INITIALIZE_ERROR,
  REQUEST_PLANETS,
  REQUEST_PLANETS_SUCCESS,
  REQUEST_PLANETS_ERROR,
  ADD_TO_CART,
  ADD_TO_CART_SUCCESS,
  ADD_TO_CART_ERROR
}